# Day 2 ML Challenge - 9/23/2019

In [1]:
#Say I have a list (iterable) of my favourite pet names, all in lower case and I need them in uppercase. 
#Traditonally, in normal pythoning, I would do something like this:

my_pets = ['alfred', 'tabitha', 'william', 'arla']
uppered_pets = []

for pet in my_pets:
    pet_ = pet.upper()
    uppered_pets.append(pet_)

print(uppered_pets)

['ALFRED', 'TABITHA', 'WILLIAM', 'ARLA']


### [Q] Get The Same Above Output Using Map Function

In [3]:
my_pets = ['alfred', 'tabitha', 'william', 'arla']

uppered_pets = #your code here

print(uppered_pets)

### [Q] Round off the first two elements in the circle area array

In [ ]:
circle_areas = [3.56773, 5.57668, 4.00914, 56.24241, 9.01344, 32.00013]

result = #your code here

print(result)

### [Q] What is the difference between Python List and Numpy List in below scenario?

In [6]:
#import numpy as np

python_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])

#Give the output without executing the code
print(python_list + python_list) #Ans:
print('\n')
print(numpy_array + numpy_array) #Ans:

### [Q] Find the BMI for the following data set using Numpy

In [12]:
import numpy as np

height = np.round(np.random.normal(1.75, 0.20, 100), 2)
weight = np.round(np.random.normal(60.32, 15, 100), 2)

BMI = # your code here

print(BMI)

### [Q] Convert the 1-D Array into 3x3 Matrix

In [14]:
foo = np.arange(11,20)
foo = #your code here
print("3x3 Matrix of foo = \n{}\n".format(foo))

### [Q] Stack these three arrays

In [31]:
a = np.array([(1,2,3),(4,5,6)])
b = np.arange(11, 20).reshape(3, -1)
zero_line = np.zeros((1,3))

c = #your code here

print("c = np.vstack((a,b, zero_line)) = \n{}\n".format(c))

# Output should look like:
# [[ 1.  2.  3.]
# [ 4.  5.  6.]
# [11. 12. 13.]
# [14. 15. 16.]
# [17. 18. 19.]
# [ 0.  0.  0.]]

### [Q] You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.

##### Input Format
##### A single line of input containing space separated numbers.
##### Output Format
##### Print the reverse NumPy array with type float.
##### Sample Input: 1 2 3 4 -8 -10
##### Sample Output: [-10.  -8.   4.   3.   2.   1.]

In [ ]:
#Your Complete Code Here